/**
 * AgriVerse AI Universal Export & Pathology Report Engine
 * Generates valid, non-corrupt UTF-8 PDF, DOCX, TXT, CSV, JSON, Excel, and Markdown reports.
 */

export function exportTextReport(title, data, aiSummary = "") {
  const textContent = `===========================================================
               AGRIVERSE AI - ${title.toUpperCase()}
===========================================================
Report Generated: ${new Date().toLocaleString()}
Engine          : AgriVerse AI OS (Ollama qwen:latest & Local HF)

-----------------------------------------------------------
1. MODULE SUMMARY & EXECUTIVE OVERVIEW
-----------------------------------------------------------
${aiSummary || "No AI summary attached to this export."}

-----------------------------------------------------------
2. MODULE DATA METRICS & CONTENT
-----------------------------------------------------------
${typeof data === 'string' ? data : JSON.stringify(data, null, 2)}

===========================================================
AgriVerse AI Smart Agriculture Operating System
===========================================================
`;

  downloadBlob(textContent, `AgriVerse_${cleanFilename(title)}.txt`, 'text/plain;charset=utf-8');
}

export function exportMarkdownReport(title, data, aiSummary = "") {
  const mdContent = `# 🌿 AgriVerse AI - ${title}

**Generated Date:** ${new Date().toLocaleString()}  
**Engine:** AgriVerse AI Local Model Pipeline (Ollama \`qwen:latest\` & HF)

---

## 📊 Executive Summary & AI Findings
${aiSummary || "No AI summary generated for this report."}

---

## 📈 Module Telemetry & Data
\`\`\`json
${typeof data === 'string' ? data : JSON.stringify(data, null, 2)}
\`\`\`

---
*Report auto-generated by AgriVerse AI Enterprise Platform.*
`;

  downloadBlob(mdContent, `AgriVerse_${cleanFilename(title)}.md`, 'text/markdown;charset=utf-8');
}

export function exportJSONReport(title, data, aiSummary = "") {
  const payload = {
    report_title: title,
    generated_at: new Date().toISOString(),
    system_version: "AgriVerse AI v1.0 Ultimate",
    ai_summary: aiSummary,
    telemetry_data: data
  };

  downloadBlob(JSON.stringify(payload, null, 2), `AgriVerse_${cleanFilename(title)}.json`, 'application/json;charset=utf-8');
}

export function exportCSVReport(title, data) {
  let csvRows = [];
  if (Array.isArray(data)) {
    if (data.length > 0 && typeof data[0] === 'object') {
      const headers = Object.keys(data[0]);
      csvRows.push(headers.join(','));
      for (const row of data) {
        const values = headers.map(header => {
          const val = row[header];
          return `"${String(val ?? '').replace(/"/g, '""')}"`;
        });
        csvRows.push(values.join(','));
      }
    }
  } else if (typeof data === 'object' && data !== null) {
    csvRows.push('Metric,Value');
    for (const [key, val] of Object.entries(data)) {
      csvRows.push(`"${key}","${String(val).replace(/"/g, '""')}"`);
    }
  } else {
    csvRows.push('Content');
    csvRows.push(`"${String(data).replace(/"/g, '""')}"`);
  }

  const csvContent = '\ufeff' + csvRows.join('\n');
  downloadBlob(csvContent, `AgriVerse_${cleanFilename(title)}.csv`, 'text/csv;charset=utf-8');
}

export function exportExcelReport(title, data, aiSummary = "") {
  const htmlTable = buildHTMLTable(data);
  const excelContent = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
    <head>
      <meta charset="utf-8"/>
      <!--[if gte mso 9]>
      <xml>
        <x:ExcelWorkbook>
          <x:ExcelWorksheets>
            <x:ExcelWorksheet>
              <x:Name>${title.slice(0, 30)}</x:Name>
              <x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions>
            </x:ExcelWorksheet>
          </x:ExcelWorksheets>
        </x:ExcelWorkbook>
      </xml>
      <![endif]-->
      <style>
        body { font-family: Arial, sans-serif; }
        th { background-color: #10b981; color: white; font-weight: bold; }
        td { border: 1px solid #cbd5e1; padding: 6px; }
      </style>
    </head>
    <body>
      <h2>AgriVerse AI - ${title}</h2>
      <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
      ${aiSummary ? `<div><h3>AI Summary</h3><p>${aiSummary}</p></div>` : ''}
      <h3>Module Data</h3>
      ${htmlTable}
    </body>
    </html>
  `;

  downloadBlob('\ufeff' + excelContent, `AgriVerse_${cleanFilename(title)}.xls`, 'application/vnd.ms-excel;charset=utf-8');
}

export function exportWordDocReport(title, data, aiSummary = "") {
  const htmlContent = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset="utf-8"/>
      <title>AgriVerse AI Report</title>
      <style>
        body { font-family: Arial, sans-serif; color: #0f172a; padding: 20px; }
        h1 { color: #059669; border-bottom: 2px solid #059669; padding-bottom: 5px; }
        h2 { color: #0284c7; margin-top: 20px; }
        .summary-box { background: #f0fdf4; border-left: 4px solid #10b981; padding: 12px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #cbd5e1; padding: 8px; font-size: 13px; }
        th { background: #f1f5f9; text-align: left; }
      </style>
    </head>
    <body>
      <h1>🌿 AgriVerse AI - ${title}</h1>
      <p><strong>Generated Date:</strong> ${new Date().toLocaleString()}</p>
      
      ${aiSummary ? `<div class="summary-box"><h2>Executive Summary & AI Findings</h2><p>${aiSummary.replace(/\n/g, '<br/>')}</p></div>` : ''}

      <h2>Telemetry Data Records</h2>
      ${buildHTMLTable(data)}

      <hr style="margin-top: 40px;" />
      <p style="font-size: 11px; color: #64748b;">Report generated by AgriVerse AI Enterprise Agriculture Platform.</p>
    </body>
    </html>
  `;

  downloadBlob('\ufeff' + htmlContent, `AgriVerse_${cleanFilename(title)}.docx`, 'application/msword;charset=utf-8');
}

export function exportPDFReport(title, data, aiSummary = "") {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert("Please allow popups to save/print the PDF report.");
    return;
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8"/>
      <title>AgriVerse AI Report - ${title}</title>
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #0f172a; line-height: 1.6; }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid #10b981; padding-bottom: 15px; margin-bottom: 25px; }
        .title { font-size: 22px; font-weight: bold; color: #065f46; }
        .badge { background: #d1fae5; color: #047857; font-weight: bold; padding: 4px 12px; border-radius: 6px; font-size: 12px; }
        .section { margin-bottom: 25px; }
        .section-title { font-size: 16px; font-weight: bold; color: #0284c7; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #cbd5e1; padding: 10px; text-align: left; font-size: 12px; }
        th { background: #f8fafc; font-weight: bold; }
        .summary-text { background: #f0fdf4; border-left: 4px solid #10b981; padding: 15px; border-radius: 6px; font-size: 13px; white-space: pre-wrap; }
        .footer { margin-top: 40px; font-size: 11px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 15px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="title">🌿 AgriVerse AI — ${title}</div>
        <div class="badge">OFFICIAL AI REPORT</div>
      </div>

      <div class="section">
        <div class="section-title">1. Report Information</div>
        <table>
          <tr><th>Module Name</th><td>${title}</td></tr>
          <tr><th>Generated Date</th><td>${new Date().toLocaleString()}</td></tr>
          <tr><th>Location</th><td>Vellore, Tamil Nadu, India</td></tr>
          <tr><th>AI Engine</th><td>Local Ollama (qwen:latest) & Hugging Face Store</td></tr>
        </table>
      </div>

      ${aiSummary ? `
      <div class="section">
        <div class="section-title">2. Executive Summary & AI Findings</div>
        <div class="summary-text">${aiSummary}</div>
      </div>
      ` : ''}

      <div class="section">
        <div class="section-title">3. Module Data Details</div>
        ${buildHTMLTable(data)}
      </div>

      <div class="footer">
        AgriVerse AI OS • Enterprise Local Model Store • Use browser print (Ctrl+P) to Save as PDF
      </div>

      <script>
        window.onload = function() { window.print(); }
      </script>
    </body>
    </html>
  `);
  printWindow.document.close();
}

function cleanFilename(str) {
  return String(str || 'Report').replace(/[^a-zA-Z0-9_\-]/g, '_');
}

function downloadBlob(content, filename, contentType) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function buildHTMLTable(data) {
  if (Array.isArray(data)) {
    if (data.length === 0) return '<p>No records available.</p>';
    if (typeof data[0] === 'object' && data[0] !== null) {
      const headers = Object.keys(data[0]);
      return `
        <table>
          <thead>
            <tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr>
          </thead>
          <tbody>
            ${data.map(row => `
              <tr>${headers.map(h => `<td>${row[h] !== undefined ? String(row[h]) : ''}</td>`).join('')}</tr>
            `).join('')}
          </tbody>
        </table>
      `;
    }
    return `<ul>${data.map(item => `<li>${String(item)}</li>`).join('')}</ul>`;
  }
  if (typeof data === 'object' && data !== null) {
    const entries = Object.entries(data);
    return `
      <table>
        <thead>
          <tr><th>Parameter</th><th>Value</th></tr>
        </thead>
        <tbody>
          ${entries.map(([k, v]) => `
            <tr><td><strong>${k}</strong></td><td>${typeof v === 'object' ? JSON.stringify(v) : String(v)}</td></tr>
          `).join('')}
        </tbody>
      </table>
    `;
  }
  return `<p>${String(data)}</p>`;
}
